services:
  - type: web
    name: live-bid-dash
    env: docker
    plan: free
    region: oregon
    branch: master
    repo: https://github.com/a6uzar/Assignment_INE.git
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
    scaling:
      minInstances: 1
      maxInstances: 3
