// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Automatic environment detection
const isProduction = import.meta.env.PROD ||
  window.location.hostname !== 'localhost' &&
  window.location.hostname !== '127.0.0.1';

// Use production Supabase for deployed environments, local for development
const SUPABASE_URL = isProduction
  ? "https://rbsvkrlzxlqnvoxbvnvb.supabase.co"
  : "http://127.0.0.1:54321";

const SUPABASE_PUBLISHABLE_KEY = isProduction
  ? "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJic3Zrcmx6eGxxbnZveGJ2bnZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNzc1MjMsImV4cCI6MjA3MDg1MzUyM30.CKOCAkzs3cXlvNiIr-mfxHmWIg1ITJMbC5hQQqELSog"
  : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0";

// Only log in development
if (!isProduction) {
  console.log('🔧 Development Mode - Using Local Supabase:', SUPABASE_URL);
} else {
  console.log('🚀 Production Mode - Using Remote Supabase');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});